### ISSUE TITLE
RB1 Patch Ark unable to be extracted

### ISSUE THREAD

**Issue by AddyMills** [PikminGuts92/Mackiloha#11]
Whenever I try to extract RB1's patch v1.07 for PS3, I get the following error:
```

Unhandled exception. System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length. (Parameter 'value')
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at Mackiloha.AwesomeReader.ReadInt32()
   at Mackiloha.Ark.ArkFile.ReadStringIndicies(AwesomeReader ar)
   at Mackiloha.Ark.ArkFile.ParseHeader(String input, Stream stream)
   at Mackiloha.Ark.ArkFile.FromFile(String input)
   at ArkHelper.Apps.Ark2DirApp.Parse(Ark2DirOptions op)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at ArkHelper.Program.Main(String[] args)

```
This is using the -s and -a commands, but it doesn't work for any combination of commands.

It's strange since every other hdr file before and after seems to work, but this is the only exception. The same seems to happen for the latest RB1 update for 360.

**Comment by PikminGuts92** [comment]
This is because Harmonix used two versions of the v4 ark header. Some track packs and apparently the RB1 updates used a _broken_ version with the offset sizes being of different data types (e.g. 32-bit vs 64-bit).

Luckily @maxton already documented this quirk in his GameArchives library so I can easily add unpack support for it. 
https://github.com/maxton/GameArchives/blob/97875280485af067da6adebed5299beaac302fda/Library/Ark/ArkPackage.cs#L154


The difficulty would implementing a good way to denote which v4 type to use when repacking as the current interface uses an integer value as input. Since this is such an edge case I'd opt to not worry about that for now.

But assuming you intend to repack the RB1 update then I would suggest using version 3. Since the base game uses v3 ark header it should have compatibility for it.

**Comment by PikminGuts92** [comment]
I added unpack support for arks with the _broken_ v4 header.

You can download a build for it on [AppVeyor](https://ci.appveyor.com/project/PikminGuts92/mackiloha/branch/master/artifacts) until I publish a regular GitHub release.

**Comment by AddyMills** [comment]
Amazing, it works now! Thanks very much for that detailed explanation, it's interesting to see how each iteration of ARK changed.
